### PR TITLE
feat: add meta frameworks support

### PR DESCRIPTION
**Pull request by johnsoncodehk**
~~Search meta framework languages that support typescript embedded language based on grammars property in language extension package.json.~~ Refactored to simpler dynamic registration.

For people who need to use this PR in advance (unzip it and drag to VSCode extension sidebar):
[pretty-ts-errors-0.2.4-pr2.vsix.zip](https://github.com/yoavbls/pretty-ts-errors/files/11215170/pretty-ts-errors-0.2.4-pr2.vsix.zip)

### CODE REVIEW

**Review by yoavbls — COMMENTED** [review]
Hey @johnsoncodehk, Thank you so much for this contribution! 😀
I didn't expect anyone to open a PR so fast, I just published it and started working 
on support for Astro, Svelte and Vue (I didn't think about mdx), and when I ended testing it, I saw your PR!
So I caused you a few conflicts, do you want me to update them in your PR or do it yourself?
Thanks :)

**Comment by johnsoncodehk** [comment]
I can do it. :)

**Review by yoavbls — APPROVED** [review]
Looks good! 
Thank you 🙂

**Comment by johnsoncodehk** [comment]
Thank you for your work. This is very great. :)

**Pull request merged**
